name: .NET Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        #with:
        #  dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Restore
        run: |
          dotnet restore ./src/DummyGame/DummyGame.csproj
          dotnet restore ./src/Launcher/Launcher.csproj

      - name: Build
        run: |
          dotnet build ./src/DummyGame/DummyGame.csproj --configuration Release --no-restore
          dotnet build ./src/Launcher/Launcher.csproj  --configuration Release --no-restore

      - name: Publish (both, framework-dependent)
        run: |
          dotnet publish ./src/DummyGame/DummyGame.csproj -c Release -o ./publish --no-restore
          dotnet publish ./src/Launcher/Launcher.csproj  -c Release -o ./publish --no-restore

      - name: Prepare Electron bundled DummyGame
        run: |
          dotnet publish ./src/DummyGame/DummyGame.csproj -c Release -o ./electron/build-resources/dummygame --no-restore

      - name: Install Electron dependencies
        run: |
          cd electron
          npm install --no-audit --no-fund

      - name: Build Electron (installer)
        run: |
          cd electron
          npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: DiscordFakeGameLauncher-Setup
          path: |
            electron/dist
